### ISSUE TITLE
Enhancements to formula calculation

### ISSUE THREAD

**Issue by kurukimi** [aalto-grades/base-repository#547]
- Formula calculation for grades should end up with range 0-5 
- Should we be able to differentiate between grade and points? How to handle points? (e.g. points in range 0-100, not 0-5)
- rise bonus formula could have field for setting the amount of the bonus (currently 1)

**Comment by no-comma** [comment]
I'm not currently working on the project, but here I am anyway so I may as well comment on this topic because I have things to say.

> Should we be able to differentiate between grade and points? How to handle points? (e.g. points in range 0-100, not 0-5)

Unless teachers have explicitly requested this, I don't see any good reason to differentiate between grades and points. Users are already capable to setting any range they want for the grades of attainments, such as 0-5, 0-1, 0-176, and so on, including deciding whether the grades for the attainment are exclusively integers or whether floats are permitted too. This allows us to cover all possible grade and point scales generically.

If teachers do want grades and points to be differentiated, I think it's best left as a mere UI feature which has no bearing on the actual grade calculation. One option would be to allow teachers to set whether each attainment takes in "points" or "grades," which will simply determine whether the numbers are called "points" or "grades" in the UI. The users will see "points" or "grades," whereas from a technical point of view there are only "numbers."

**Comment by kurukimi** [comment]
Thanks @no-comma . I think this 'idea' about differentiating grades and points came up (from a teacher) when discussing the basic flow of a teacher using this grades system.  
I also think that is a good idea to implement it only as an UI feature as you said if more teachers would see it be more intuitive .
