### ISSUE TITLE
Logout Procedure cleanup

### ISSUE THREAD

**Issue by gubo97000** [aalto-grades/base-repository#573]
Logging out from an account and logging with another will redirect to the homepage without reloading the content, and showing still the data of the previous account.

We need to test and understand where the cleanup/refresh is needed.

**Comment by bntti** [comment]
The problem is caused by `useGetRefreshToken` cache never being invalidated
https://github.com/aalto-grades/base-repository/blob/11cdd0c1ceeefb9df6fcc416625639904ea3ab66/client/src/components/auth/PrivateRoute.tsx#L24-L31
The same lines also cause the bug that requires the user to login twice, due to `useGetRefreshToken().data` being null. Might be due to some bad timings.

One way to fix the wrong account data issue would be to add this line to the logout function.
```ts
queryClient.invalidateQueries({queryKey: ['refresh-token']});
```
https://github.com/aalto-grades/base-repository/blob/11cdd0c1ceeefb9df6fcc416625639904ea3ab66/client/src/components/auth/UserButton.tsx#L23-L28
